##Numpy

Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. If you are already familiar with MATLAB, you might find this [tutorial](http://wiki.scipy.org/NumPy_for_Matlab_Users) useful to get started with Numpy.

To use Numpy, we first need to import the `numpy` package:

In [1]:
import numpy as np

###Arrays

A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

We can initialize numpy arrays from nested Python lists, and access elements using square brackets:

In [2]:
a = np.array([1, 2, 3])  # 新建一個一維陣列
print(type(a), a.shape, a[0], a[1], a[2]) # 列出a的類型、維度、第1 2 3值的元素
a[0] = 5                 # 更改a[0]的元素
print(a)                  

<class 'numpy.ndarray'> (3,) 1 2 3
[5 2 3]


In [3]:
b = np.array([[1,2,3],[4,5,6]])   # 建立一個二維陣列
print(b)

[[1 2 3]
 [4 5 6]]


In [4]:
print(b.shape) # 印出陣列b的維度
print(b[0, 0], b[0, 1], b[1, 0]) # 印出陣列b的值

(2, 3)
1 2 4


Numpy also provides many functions to create arrays:

In [5]:
a = np.zeros((2,2))  # 建立一個全是0的2*2陣列
print(a)

[[0. 0.]
 [0. 0.]]


In [6]:
b = np.ones((1,2))   # 建立一個全是1的一維陣列
print(b)

[[1. 1.]]


In [7]:
c = np.full((2,2), 7) # 建立一個值全為7的常量陣列
print(c)

[[7 7]
 [7 7]]


In [8]:
d = np.eye(2)        # 建立一個對角線為1，其餘位置為0的二維陣列
print(d)

[[1. 0.]
 [0. 1.]]


In [9]:
e = np.random.random((2,2)) # 建立一個填入亂數值的二維陣列
print(e)

[[0.59398676 0.17112804]
 [0.22450463 0.2965411 ]]


###Array indexing

Numpy offers several ways to index into arrays.

Slicing: Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

In [10]:
import numpy as np

#  創建一個3*4的二維陣列
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# 取出第一列的第二第三個
# 取出第二列的第二第三個
# [[2 3]
#  [6 7]]
b = a[0:2, 1:3]
print(b)

[[2 3]
 [6 7]]


A slice of an array is a view into the same data, so modifying it will modify the original array.

In [11]:
print(a[0, 1])
b[0, 0] = 77    # b[0，0]與[0，1]是相同的數據
print(a[0, 1]) 

2
77


You can also mix integer indexing with slice indexing. However, doing so will yield an array of lower rank than the original array. Note that this is quite different from the way that MATLAB handles array slicing:

In [12]:
# 創建一個3*4的二維陣列
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Two ways of accessing the data in the middle row of the array.
Mixing integer indexing with slices yields an array of lower rank,
while using only slices yields an array of the same rank as the
original array:

In [13]:
row_r1 = a[1, :]    #印出第二列，並列出維度
row_r2 = a[1:2, :]  #印出第二列，並列出維度
row_r3 = a[[1], :]  #印出第二列，並列出維度
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)
print(row_r3, row_r3.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[[5 6 7 8]] (1, 4)


In [14]:
# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1] #印出第二列，並列出維度
col_r2 = a[:, 1:2] #印出第二列，並列出維度
print(col_r1, col_r1.shape)
print()
print(col_r2, col_r2.shape)

[ 2  6 10] (3,)

[[ 2]
 [ 6]
 [10]] (3, 1)


Integer array indexing: When you index into numpy arrays using slicing, the resulting array view will always be a subarray of the original array. In contrast, integer array indexing allows you to construct arbitrary arrays using the data from another array. Here is an example:

In [15]:
a = np.array([[1,2], [3, 4], [5, 6]])

# 整數陣列索引的示例
# 返回的陣列將具有維度（3，）和
print(a[[0, 1, 2], [0, 1, 0]])

# 上面的整數陣列索引示例等同於此：
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))

[1 4 5]
[1 4 5]


In [16]:
# 使用整數陣列索引時，可以重複使用相同的索引
# 來源陣列中的元素：:
print(a[[0, 0], [1, 1]])

# 等於前面的整數陣列索引示例
print(np.array([a[0, 1], a[0, 1]]))

[2 2]
[2 2]


One useful trick with integer array indexing is selecting or mutating one element from each row of a matrix:

In [17]:
# 創建一個新陣列，我們將從中選擇元素
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [18]:
# 建立索引陣列
b = np.array([0, 2, 0, 1])

# 使用b中的索引從a的每一列中選擇一個元素
print(a[np.arange(4), b])  # Prints "[ 1  6  7 11]"

[ 1  6  7 11]


In [19]:
# 使用b中的索引對a的每一列中的一個元素進行相加
a[np.arange(4), b] += 10
print(a)

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


Boolean array indexing: Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition. Here is an example:

In [20]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)         #查找大於2的元素；
                    #這將返回相同的布林值的numpy陣列
                    #其中bool_idx的每個插槽都告訴a的元素是否大於2。

print(bool_idx)

[[False False]
 [ True  True]
 [ True  True]]


In [21]:
#我們使用布林振烈索引來構建秩維度為1的陣列
#由與True值相對應的元素組成
#bool_idx
print(a[bool_idx])

# 我們可以在一個簡潔的陳述中完成上述所有操作:
print(a[a > 2])

[3 4 5 6]
[3 4 5 6]


For brevity we have left out a lot of details about numpy array indexing; if you want to know more you should read the documentation.

###Datatypes

Every numpy array is a grid of elements of the same type. Numpy provides a large set of numeric datatypes that you can use to construct arrays. Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype. Here is an example:

In [22]:
x = np.array([1, 2]) #讓numpy選擇陣列類型
y = np.array([1.0, 2.0])  #讓numpy選擇陣列類型
z = np.array([1, 2], dtype=np.int64)  #強制使用特定資料類型

print(x.dtype, y.dtype, z.dtype)

int64 float64 int64


You can read all about numpy datatypes in the [documentation](http://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html).

###Array math

Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module:

In [23]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# 按元素求和；都列出陣列
print(x + y)
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [24]:
# 元素相減；都列出陣列
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [25]:
# 元素相乘；都列出陣列
print(x * y)
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [26]:
# 元素相除；都列出陣列
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [27]:
# 元素開平方；都列出陣列
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


Note that unlike MATLAB, `*` is elementwise multiplication, not matrix multiplication. We instead use the dot function to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices. dot is available both as a function in the numpy module and as an instance method of array objects:

In [28]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# 列出向量的內積；都產生219
print(v.dot(w))
print(np.dot(v, w))

219
219


You can also use the `@` operator which is equivalent to numpy's `dot` operator.

In [29]:
print(v @ w)

219


In [30]:
# 矩陣/向量乘積；都產生1維陣列[29 67]
print(x.dot(v))
print(np.dot(x, v))
print(x @ v)

[29 67]
[29 67]
[29 67]


In [31]:
# 矩陣/向量乘積；都產生1維陣列[29 67]
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))
print(x @ y)

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


Numpy provides many useful functions for performing computations on arrays; one of the most useful is `sum`:

In [32]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))  #計算所有元素的總和；列出“10”
print(np.sum(x, axis=0))  #計算每一行的總和；打印“ [4 6]”
print(np.sum(x, axis=1))  #計算每一列的總和；打印“ [3 7]”

10
[4 6]
[3 7]


You can find the full list of mathematical functions provided by numpy in the [documentation](http://docs.scipy.org/doc/numpy/reference/routines.math.html).

Apart from computing mathematical functions using arrays, we frequently need to reshape or otherwise manipulate data in arrays. The simplest example of this type of operation is transposing a matrix; to transpose a matrix, simply use the T attribute of an array object:

In [33]:
print(x)
print("transpose\n", x.T) #將x變成轉置矩陣

[[1 2]
 [3 4]]
transpose
 [[1 3]
 [2 4]]


In [34]:
v = np.array([[1,2,3]])
print(v )
print("transpose\n", v.T) #將v變成轉置矩陣

[[1 2 3]]
transpose
 [[1]
 [2]
 [3]]


###Broadcasting

Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.

For example, suppose that we want to add a constant vector to each row of a matrix. We could do it like this:

In [35]:
#我們將向量v添加到矩陣x的每一行，
#將結果存儲在矩陣y中
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   #創建一個維度與x相同的空矩陣

# 通過explicit loop將向量v添加到矩陣x的每一行
for i in range(4):
    y[i, :] = x[i, :] + v

print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


This works; however when the matrix `x` is very large, computing an explicit loop in Python could be slow. Note that adding the vector v to each row of the matrix `x` is equivalent to forming a matrix `vv` by stacking multiple copies of `v` vertically, then performing elementwise summation of `x` and `vv`. We could implement this approach like this:

In [36]:
vv = np.tile(v, (4, 1))  #堆疊v的4個副本
print(vv)                # Prints [[1 0 1]
                         # [1 0 1]
                         # [1 0 1]
                         # [1 0 1]]"

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]


In [37]:
y = x + vv  #逐元素添加x和vv
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


Numpy broadcasting allows us to perform this computation without actually creating multiple copies of v. Consider this version, using broadcasting:

In [38]:
import numpy as np

#我們將向量v添加到矩陣x的每一行，
#將結果存儲在矩陣y中
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # 將v添加到x的每一行
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


The line `y = x + v` works even though `x` has shape `(4, 3)` and `v` has shape `(3,)` due to broadcasting; this line works as if v actually had shape `(4, 3)`, where each row was a copy of `v`, and the sum was performed elementwise.

Broadcasting two arrays together follows these rules:

1. If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s until both shapes have the same length.
2. The two arrays are said to be compatible in a dimension if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension.
3. The arrays can be broadcast together if they are compatible in all dimensions.
4. After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of shapes of the two input arrays.
5. In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension

If this explanation does not make sense, try reading the explanation from the [documentation](http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html) or this [explanation](http://wiki.scipy.org/EricsBroadcastingDoc).

Functions that support broadcasting are known as universal functions. You can find the list of all universal functions in the [documentation](http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs).

Here are some applications of broadcasting:

In [39]:
#計算矩陣的外積
v = np.array([1,2,3])  #v的維度為（3，）
w = np.array([4,5])    #w的維度為(2,)
#為了計算外部乘積，我們首先將v重整為列
#維度的向量（3，1）;然後我們可以針對w產生
#維度（3，2）的輸出，它是v和w的外積：

print(np.reshape(v, (3, 1)) * w)

[[ 4  5]
 [ 8 10]
 [12 15]]


In [40]:
#向矩陣的每一列添加一個向量
x = np.array([[1,2,3], [4,5,6]])
#x的維度為（2，3），而v的維度為（3，），因此它們加到（2，3），
#給出以下矩陣：

print(x + v)

[[2 4 6]
 [5 7 9]]


In [41]:
#向矩陣的每一行添加一個向量
#x的維度為（2，3），w的維度為（2，）。
#如果我們對x進行轉置，則它的維度為（3，2）並且可以加入
#對w產生維度（3，2）的結果;轉置此結果
#產生維度（2，3）的最終結果，即矩陣x
#添加到每一行的向量w。給出以下矩陣：

print((x.T + w).T)

[[ 5  6  7]
 [ 9 10 11]]


In [42]:
#另一個解決方案是將w重整為維度為（2，1）的列向量；
#然後我們可以直接針對x廣播它以產生相同的輸出。
print(x + np.reshape(w, (2, 1)))

[[ 5  6  7]
 [ 9 10 11]]


In [43]:
#將矩陣乘以一個常數：
#x的維度為（2，3）。 Numpy將標量視為shape（）的陣列；
#這些可以一起加入將（2，3）成形，產生以下陣列：
print(x * 2)

[[ 2  4  6]
 [ 8 10 12]]


Broadcasting typically makes your code more concise and faster, so you should strive to use it where possible.

This brief overview has touched on many of the important things that you need to know about numpy, but is far from complete. Check out the [numpy reference](http://docs.scipy.org/doc/numpy/reference/) to find out much more about numpy.